# Generated by Django 4.2.10 on 2024-04-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metiers",
            fields=[
                ('id_metiers', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entreprisesrecrutent', models.TextField(blank=True, null=True)),
                ('salairemoyen', models.TextField(blank=True, null=True)),
                ('competencescles', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('images_pc', models.CharField(blank=True, max_length=255, null=True)),
                ('principales_missions', models.TextField(blank=True, null=True)),
                ('images_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('images_tablettes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "metiers",
                "managed": False,
            },
        ),
    ]
