# Generated by Django 4.2.10 on 2024-03-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metiers',
            fields=[
                ('id_metiers', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entreprisesrecrutent', models.TextField(blank=True, null=True)),
                ('salairemoyen', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/metiers/')),
                ('competencescles', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metiers',
                'managed': False,
            },
        ),
    ]
