# Generated by Django 4.2.10 on 2024-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('faculte_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('condition_admission', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/facultes')),
            ],
            options={
                'db_table': 'faculte',
                'managed': False,
            },
        ),
    ]
