# Generated by Django 4.2.10 on 2025-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
