# Generated by Django 4.2.10 on 2025-02-10 11:03

from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_image_desktop_notification_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expiration_date',
            field=models.DateTimeField(default=notification.models.two_months_from_now),
        ),
    ]
