# Generated by Django 4.2.10 on 2024-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recherches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(blank=True, null=True)),
                ('mots_cles', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recherches',
                'managed': False,
            },
        ),
    ]
