# Generated by Django 4.2.10 on 2024-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(max_length=255)),
                ('montant', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'consultation',
                'managed': False,
            },
        ),
    ]
