# Generated by Django 4.2.10 on 2024-05-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='account_verification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
