# Generated by Django 4.2.10 on 2024-05-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_utilisateur_account_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='account_verification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
