# Generated by Django 4.2.10 on 2024-08-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_utilisateur_account_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='expert_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_expert',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
