# Generated by Django 4.2.10 on 2024-04-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('universite_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('pays', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('descriptif', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('site_web', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('images_pc', models.TextField(blank=True, null=True)),
                ('images_telephone', models.TextField(blank=True, null=True)),
                ('images_tablettes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'universite',
                'managed': False,
            },
        ),
    ]
