# Generated by Django 4.2.10 on 2024-08-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('domaine', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=255)),
                ('adresse_mail', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('annee_experience', models.IntegerField()),
                ('nombre_personne_a_noter', models.IntegerField(blank=True, null=True)),
                ('note_moyenne', models.FloatField(blank=True, null=True)),
                ('montant_commission', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'experts',
                'managed': False,
            },
        ),
    ]
