# Generated by Django 4.2.10 on 2024-03-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('photo_de_profil', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'administrateur',
                'managed': False,
            },
        ),
    ]
