# Generated by Django 4.2.10 on 2024-04-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filieres",
            fields=[
                ('filieres_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('descriptif', models.TextField()),
                ('duree', models.IntegerField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('langue_enseignement', models.CharField(max_length=50)),
                ('diplome_delivre', models.CharField(max_length=255)),
                ('images_pc', models.CharField(blank=True, max_length=255, null=True)),
                ('images_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('images_tablettes', models.CharField(blank=True, max_length=255, null=True)),
                ('centre_interet', models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "filieres",
                "managed": False,
            },
        ),
    ]
