# Generated by Django 4.2.10 on 2024-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filieres",
            fields=[
                ("filieres_id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("descriptif", models.TextField()),
                ("duree", models.IntegerField()),
                ("cout", models.DecimalField(decimal_places=2, max_digits=10)),
                ("langue_enseignement", models.CharField(max_length=50)),
                ("diplome_delivre", models.CharField(max_length=255)),
                (
                    "imageurl",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/filieres"
                    ),
                ),
            ],
            options={
                "db_table": "filieres",
                "managed": False,
            },
        ),
    ]
