# Generated by Django 4.2.10 on 2024-09-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualit',
            options={'managed': True},
        ),
    ]
