# Generated by Django 4.2.10 on 2024-09-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_alter_actualit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualit',
            options={'managed': False},
        ),
    ]
